# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/switch.battlefiesta.in
cert = /etc/letsencrypt/live/switch.battlefiesta.in/cert.pem
privkey = /etc/letsencrypt/live/switch.battlefiesta.in/privkey.pem
chain = /etc/letsencrypt/live/switch.battlefiesta.in/chain.pem
fullchain = /etc/letsencrypt/live/switch.battlefiesta.in/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b4dcaf956e41482ba4e76b4db35063a6
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
