services:
  backend:
    build: ./server
    container_name: server
    restart: always
    env_file:
      - ./server/.env
    networks:
      - accunet

  frontend:
    build: ./frontend
    container_name: accufrontend
    restart: always
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - accunet

networks:
  accunet:
    external: true
